# Generated by Django 5.0.2 on 2024-02-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
