# Generated by Django 5.0.2 on 2024-02-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AS2', '0002_alter_usercredentials_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='user',
        ),
    ]
