# Generated by Django 5.0.2 on 2024-02-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AS2', '0003_remove_usercredentials_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('bucketid', models.IntegerField()),
                ('data', models.TextField()),
            ],
        ),
    ]
